YML file

diff --git a/.github/workflows/R-CMD-check.yml b/.github/workflows/R-CMD-check.yml
--- a/.github/workflows/R-CMD-check.yml
+++ b/.github/workflows/R-CMD-check.yml
@@ -34,35 +34,32 @@ jobs:
     steps:
       - uses: actions/checkout@v3
 
+      # ----------------------- Set up R -----------------------
       - name: Set up R
         uses: r-lib/actions/setup-r@v2
         with:
           r-version: ${{ matrix.r }}
           http-user-agent: ${{ matrix.http-user-agent }}
 
-      # ----------------- TinyTeX setup for macOS & Linux -----------------
-      - name: Install TinyTeX (macOS & Linux)
-        if: runner.os != 'Windows'
+      # ----------------------- TinyTeX setup -----------------------
+      - name: Install TinyTeX
         run: |
           Rscript -e "install.packages('tinytex')"
           Rscript -e "tinytex::install_tinytex(force = TRUE)"
           Rscript -e "tinytex::tlmgr_install(c('latex-bin','pdftex','babel-english','xcolor','framed','inconsolata'))"
-          
-      # ----------------- TinyTeX setup for Windows -----------------
-      - name: Install TinyTeX (Windows)
-        if: runner.os == 'Windows'
+
+      - name: Add TinyTeX to PATH
         run: |
-          Rscript -e "install.packages('tinytex')"
-          Rscript -e "tinytex::install_tinytex(force = TRUE)"
-          Rscript -e "tinytex::tlmgr_install(c('latex-bin','pdftex','babel-english','xcolor','framed','inconsolata'))"
-          echo "C:/Users/runneradmin/AppData/Roaming/TinyTeX/bin/windows" >> $env:GITHUB_PATH
+          if [ "${{ runner.os }}" = "Windows" ]; then
+            echo "C:/Users/runneradmin/AppData/Roaming/TinyTeX/bin/windows" >> $env:GITHUB_PATH
+          elif [ "${{ runner.os }}" = "Linux" ]; then
+            echo "$HOME/bin/TinyTeX/bin/*" >> $GITHUB_PATH
+          fi
+          # Debug
+          which pdflatex
+          pdflatex --version || echo "pdflatex not found"
 
-      # ----------------- Check pdflatex version (Windows) -----------------
-      - name: Check pdflatex version
-        if: runner.os == 'Windows'
-        run: pdflatex --version
-
-      # ----------------- Install tidy -----------------
+      # ------------------------ Install tidy ------------------------
       - name: Install tidy (macOS only)
         if: runner.os == 'macOS'
         run: brew install tidy-html5
@@ -71,7 +68,7 @@ jobs:
         if: runner.os == 'Linux'
         run: sudo apt-get update && sudo apt-get install -y tidy
 
-      # ----------------- Install R dependencies -----------------
+      # ------------------- Install R dependencies -------------------
       - name: Install R dependencies
         uses: r-lib/actions/setup-r-dependencies@v2
         with:
@@ -82,18 +79,9 @@ jobs:
             any::tinytex
 
       # ----------------- Run R CMD check -----------------
-      - name: Run R CMD check #(Linux & macOS - skip manual)
-        # if: runner.os != 'Windows'
+      - name: Run R CMD check
         uses: r-lib/actions/check-r-package@v2
         with:
           args: 'c("--as-cran")'
           build_args: 'c("--compact-vignettes=gs+qpdf")'
           upload-snapshots: true
-
-      # - name: Run R CMD check (Windows - skip manual)
-      #   if: runner.os == 'Windows'
-      #   uses: r-lib/actions/check-r-package@v2
-      #   with:
-      #     args: 'c("--as-cran")'
-      #     build_args: 'c("--no-manual","--compact-vignettes=gs+qpdf")'
-      #     upload-snapshots: true
